# Generated by Django 3.2.9 on 2021-11-16 22:37

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friend_code',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=12, unique=True),
        ),
    ]
