# Generated by Django 3.2.9 on 2021-12-14 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='added_users',
            field=models.ManyToManyField(blank=True, related_name='added_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='banned_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_add_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_change_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_kick',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_send_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
